### PR TITLE
added least squares for classification interactive

### PR DESCRIPTION
**Pull request by jskaza**
I incorporated Python code into lecture 07 to better illustrate the problem with using least squares for classification. We had previously relied upon the static image taken from p.186 of PRML.

### CODE REVIEW

**Comment by benrbray** [comment]
This example looks great!  Your code is a little long.  Could you shorten it and/or add some more comments to explain what you're doing?  This well help students who want to understand how the code works.

Also, what's your uniquename?

**Comment by jskaza** [comment]
Uniquename is jskaza. Yes, I'll try to shorten things up!

Thanks,
Jon

On Tuesday, February 9, 2016, Ben Bray <notifications@github.com> wrote:

> This example looks great! Your code is a little long. Could you shorten it
> and/or add some more comments to explain what you're doing? This well help
> students who want to understand how the code works.
>
> Also, what's your uniquename?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thejakeyboy/umich-eecs545-lectures/pull/5#issuecomment-182063361>
> .
>


-- 
Jonathan Skaza
Graduate Student Research Assistant (GSRA)
Department of Biostatistics
University of Michigan
jskaza.github.io

**Comment by thejakeyboy** [comment]
Hey Jon:

This does look really neat. Nice work! I was bothered by the awkward images from PRML. Yours are a lot better.

I don't want to push you too hard, but any thoughts on making the Fischer Linear Discriminant plots better? I have not idea how to layer a bar plot on top of a scatter plot, but it would be cool to see something like that visualized. (No worries if you can't figure that out)

Cheers,
Jake

**Comment by jskaza** [comment]
Sure thing. The layering could be challenging but I'll give it a try this
weekend.

Jon

On Thursday, February 11, 2016, Jacob Abernethy <notifications@github.com>
wrote:

> Hey Jon:
>
> This does look really neat. Nice work! I was bothered by the awkward
> images from PRML. Yours are a lot better.
>
> I don't want to push you too hard, but any thoughts on making the Fischer
> Linear Discriminant plots better? I have not idea how to layer a bar plot
> on top of a scatter plot, but it would be cool to see something like that
> visualized. (No worries if you can't figure that out)
>
> Cheers,
> Jake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thejakeyboy/umich-eecs545-lectures/pull/5#issuecomment-183144549>
> .
>


-- 
Jonathan Skaza
Graduate Student Research Assistant (GSRA)
Department of Biostatistics
University of Michigan
jskaza.github.io

**Comment by jskaza** [comment]
Just a heads up...I’ve been swamped lately. I plan on reviewing this code
over break. I’ll also look into the Fisher Linear Discriminant plots then.

Best,
Jon

Jonathan Skaza
Graduate Student Research Assistant (GSRA)
Department of Biostatistics
University of Michigan
jskaza.github.io

**Comment by benrbray** [comment]
I merged your original changes since there were no merge conflicts and I'm a little afraid of conflicts arising if we accidentally rename / change anything.  If / when you make additional improvements, feel free to make another pull request or modify this one.

Cheers!

**Pull request merged**
